# this is for remote build

version: '3'

services:
  verdict:
    image: "verdictproject/verdict"
    ports:
      - "8888:8888"
      - "8180:8180"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - ZEPPELIN_PORT=8180
    hostname: "verdict"
    container_name: "docker-verdict"

  presto:
    image: "verdictproject/docker-presto-with-hadoop"
    ports:
      - "8080:8080"     # presto
      - "10000:10000"   # hive
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - QUERY_MAX_MEMORY=20GB
      - QUERY_MAX_MEMORY_PER_NODE=15GB
      - QUERY_MAX_TOTAL_MEMORY_PER_NODE=35GB
      - JAVA_HEAP_SIZE=50G
    hostname: "presto"
    container_name: "docker-presto"
